#
# Dockerfile.ubuntu - part of https://github.com/katalyticIT/libfaketime_init
#

#-- definitions/build arguments
ARG BASEIMAGE=ubuntu:latest

FROM $BASEIMAGE

# update image
RUN  apt-get update && apt-get -y upgrade

# install libfaketime
RUN  apt-get -y install libfaketime

# copy runtime script and make it executable
COPY src/copyLibfaketime.sh /tmp
RUN  mkdir /app && mv /tmp/copyLibfaketime.sh /app && chmod +x /app/copyLibfaketime.sh

CMD ["/app/copyLibfaketime.sh"]
